agiledev-students-spring-2023/final-project-mealspot

front-end/package-lock.json
front-end/package.json
front-end/src/App.js
front-end/src/Fridge.js
front-end/src/GroceryList.js
front-end/src/MealPlan.js
front-end/src/Navbar.css
front-end/src/Navbar.js
front-end/src/RecipeSearch.js
front-end/src/SavedRecipes.js
front-end/src/components/App.css
front-end/src/components/App.js
front-end/src/components/Fridge.js
front-end/src/components/GroceryList.js
front-end/src/components/MealPlan.js
front-end/src/components/Navbar.css
front-end/src/components/Navbar.js
front-end/src/components/RecipeSearch.js
front-end/src/components/SavedRecipes.js

I've created a simple navbar that navigates between the pages of the app. I have also set up some blank placeholder pages for everyone to fill in (meal plan, recipe search, saved recipes, fridge, grocery list) and organized the front-end directory a little bit by adding a components folder.
The navbar is not fully styled with the icons yet, but I'll be working on that next.
I'd like to merge into master before others start working on their individual pages, so that the newly organized directory structure, as well as the blank placeholder files I created, can be used by everyone.
Thanks!
~ Charlotte

User story/22/task/21/navbar

---

front-end/package-lock.json
front-end/package.json
front-end/src/components/Navbar.css
front-end/src/components/Navbar.js

Updated navbar.css to improve the styling for the navbar. Made its width 100% and spacing of the links to be based on view width as well, so it should work for any size phone/screen. Also added some fun/informative icons to the navbar using the react-icon library.
- Charlotte

Styling and icons for navbar

---

front-end/src/components/MealPlan.css
front-end/src/components/MealPlan.js

Edited MealPlan.js and MealPlan.css to add budget tracker bar

Homepage budget tracker

---

front-end/src/components/MealPlan.js

Created dropdown for days of week in homepage

Created dropdown for days of week in homepage

---

front-end/src/components/App.js
front-end/src/components/Header.css
front-end/src/components/Header.js

Added Header.js and Header.css, and put the header in App.js so it shows throughout whole app.

Added header files and also put it in app.js

---

front-end/package.json
front-end/src/components/App.js
front-end/src/components/Navbar.css
front-end/src/components/Navbar.js
front-end/src/components/RecipeCard.css
front-end/src/components/RecipeCard.js
front-end/src/components/RecipeDisplay.css
front-end/src/components/RecipeDisplay.js
front-end/src/components/RecipeSearch.js
front-end/src/components/SavedRecipes.js
front-end/src/components/SearchBar.js

Implemented "Recipe Search" and "Saved Recipes" pages.
Those two pages both contain a "Recipe Display" component. The Recipe Display component consists of a Search Bar component and an array of Recipe Card components. Uses a mock API to simulate getting the recipe data from the backend.
Each recipe card shows the recipe's name, its total price (dynamically calculated using that recipe's data), an image, and a star icon which is filled for favorite or outlined for not favorite. The star icon is also a button that updates the database on click, but this is not fully implemented yet and will be done during the Back-end sprint.
- Charlotte

User story/6/task/29/recipe search

---

front-end/src/components/App.js
front-end/src/components/ChoosePage.css
front-end/src/components/ChoosePage.js
front-end/src/components/MealPlan.css
front-end/src/components/MealPlan.js

Added ChoosePage.js and ChoosePage.css. Added an edit button on MealPlan.js that brings you to a page to choose a recipe or add your own.

Added an edit page from MealPlan to choose or add

---

front-end/src/components/MealPlan.js

added currSpent var and changed meal plan title

---

front-end/src/components/RecipeCard.css
front-end/src/components/RecipeDisplay.css

Updated CSS for RecipeCard and RecipeDisplay to use flexbox instead of block and inline-block, so Saved Recipes and Recipe Search pages look a little nicer now.
~ Charlotte

CSS updates

---

back-end/app.js
back-end/package.json
back-end/server.js

I set up the Express back-end app.js, server.js, and package.json. I also included an example route.
~ Charlotte

set up express backend skeleton code

---

back-end/app.js
front-end/src/components/RecipeCard.js
front-end/src/components/RecipeDisplay.js
front-end/src/components/RecipeSearch.js
front-end/src/components/SavedRecipes.js

Handles saving and unsaving recipes

post routes for saved recipes and recipe search

---

back-end/app.js
front-end/src/components/Login.js
front-end/src/components/Register.js

finished post requests for login and register pages

User story/15/task/83

---

back-end/app.js
front-end/src/components/MealPlan.js

User-story/8/task/69/homepage-route

---

back-end/app.js
back-end/testFridge.json
back-end/testRecipes.json
front-end/src/components/RecipeDisplay.css
front-end/src/components/RecipeDisplay.js
front-end/src/components/RecipeSearch.js

recommended recipes feature for recipe search and saved recipes pages. Added some custom JSON fake data for testing the saved recipes page.

User story/7/task/91/recommended recipes

---

back-end/app.test.js
back-end/package.json

install mocha and chai libraries, create app.test.js

set up unit testing

---

back-end/app.js
back-end/app.test.js
back-end/package.json
back-end/test.js

unit tests for GET and POST routes of /savedrecipes and /recipesearch - valid inputs and invalid inputs.
Set up package.json so `npm test` works properly. Installed Istanbul nyc library for code coverage

fixed setup for unit tests and wrote my unit tests

---

back-end/test.js

updated unit tests to fit the updated routes

---

back-end/app.js
back-end/testRecipes.json
front-end/src/components/RecipeCard.js
front-end/src/components/RecipeDisplay.js

Reworked Recipe Search route to prepare for integration with new recipe API, fixed minor related items such as the text on the recipe details button (says save or unsave now)

User story/6/task/117/recipe api

---

front-end/src/components/RecipeDisplay.js
front-end/src/components/SearchBar.js

Fixed recipe search bar. Sorry I didn't catch this during the last sprint, when it should have been fixed. Still have a ways to go to finish planned updates to search bar functions.

fix conditions so that recipe search search bar works again

---

front-end/src/components/MealPlan.js

edited homepage to post request everytime day of week is changed

User story/8/task/69/homepage route

---

back-end/apiCall.js
back-end/app.js
back-end/testFridge.json
back-end/testRecipes.json
front-end/src/components/RecipeDisplay.js

Integrated API for recommendation feature on recipe search and saved recipes pages.

User story/6/task/117/recommendations

---

back-end/app.js
back-end/auth-routes.js
back-end/config/jwt-config.js
back-end/package.json
front-end/src/components/Login.js
front-end/src/components/Register.js

implemented login and registration

User story/15/task/118

---

back-end/app.js
back-end/auth-routes.js
back-end/models/Day.js
back-end/models/MealPlan.js
back-end/models/User.js
front-end/src/components/MealPlan.js
front-end/src/components/RecipeDisplay.js

connected homepage to the database

User-story/8/task/120/db-budget-bar

---

back-end/app.js
back-end/models/User.js
front-end/src/components/Account.js
front-end/src/components/RecipeCard.js
front-end/src/components/RecipeDisplay.js

changed saved recipes to use savedRecipes schema

---

front-end/src/components/App.js
front-end/src/components/RecipeCard.js
front-end/src/components/RecipeDisplay.js
front-end/src/components/RecipeSearch.js
front-end/src/components/SavedRecipes.js

Added loading screens to recipe search and saved recipes pages, auto-refresh when user unsaves a saved recipe, update star icon and button text when user saves/unsaves a recipe on recipe search page.
Make the app seem more polished and functional, I think!

User story/10/task/129/saved post

---

back-end/apiCall.js
back-end/app.js
front-end/public/index.html
front-end/public/manifest.json
front-end/src/components/Account.css
front-end/src/components/Account.js
front-end/src/components/App.css
front-end/src/components/ChooseSavedRecipes.css
front-end/src/components/ChooseSavedRecipes.js
front-end/src/components/MealPlan.css
front-end/src/components/MealPlan.js
front-end/src/components/RecipeCard.css
front-end/src/components/RecipeCard.js
front-end/src/components/RecipeDisplay.css
front-end/src/components/RecipeDisplay.js
front-end/src/components/RecipeSearch.js
front-end/src/components/SavedRecipes.js
front-end/src/components/SearchBar.css
front-end/src/components/SearchBar.js

get rid of ingredients on meal plan, make recipe cards look nicer, make recipe details look nicer, change some icons on the choose from saved recipes page, and more CSS updates

added page title to account page, make recipe card images square

---

front-end/src/components/MealPlan.js

fix loading bar

---

front-end/src/components/MealPlan.js

now has a spinner while waiting for recipeinfo component to load (also has spinner while waiting for api response)

add loading spinner on meal plan page

---

back-end/app.js
front-end/src/components/MealPlan.js

fix post request that was previously broken

User story/4/task/184/fix homepage

---

back-end/app.js
back-end/auth-routes.js
back-end/models/User.js
front-end/src/components/MealPlan.js
front-end/src/components/RecipeCard.js

Moved total spent money user spends into the backend.
NOTE: past users will no longer work, as they do not have the totalSpent value in their schema

User-story/8/task/203/fix-price

---

back-end/app.js
back-end/auth-routes.js

fixed price calculation and set new user weekly budget to 100 upon first register

User story/8/task/203/fix price

---

back-end/auth-routes.js
front-end/src/components/Register.js

fixed register by removing brackets around const in auth-routes.js

fixed register
